### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by Glitch31415** [wootguy/SevenKewp_plugins#1]
after doing the cstdint fix like i did for the main sevenkewp build, the build stops with this:
`
[ 20%] Building CXX object maps/pizza_ya_san/CMakeFiles/pizza_ya_san.dir/weapon_as_shotgun.cpp.o
/home/glitch/SevenKewp_plugins/maps/pizza_ya_san/weapon_as_shotgun.cpp:25:20: warning: narrowing conversion of ‘gSkillData.skilldata_t::sk_ammo_max_buckshot’ from ‘float’ to ‘int’ [-Wnarrowing]
   25 |         gSkillData.sk_ammo_max_buckshot,// iMaxAmmo1
      |         ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
[ 40%] Building CXX object maps/pizza_ya_san/CMakeFiles/pizza_ya_san.dir/weapon_as_soflam.cpp.o
[ 60%] Building CXX object maps/pizza_ya_san/CMakeFiles/pizza_ya_san.dir/weapon_as_jetpack.cpp.o
[ 80%] Building CXX object maps/pizza_ya_san/CMakeFiles/pizza_ya_san.dir/pizza_ya_san.cpp.o
gmake[2]: *** No rule to make target '/home/glitch/SevenKewp_plugins/lib/sevenkewp.so', needed by 'maps/pizza_ya_san/pizza_ya_san.so'.  Stop.
gmake[1]: *** [CMakeFiles/Makefile2:98: maps/pizza_ya_san/CMakeFiles/pizza_ya_san.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
`

**Comment by wootguy** [comment]
looks like the mod lib wasn't copied over. Something went wrong with `update_api.sh` I think. As a quick fix you can copy the sevenkewp.so that you built to the lib folder manually.

**Comment by Glitch31415** [comment]
i didn't even run update_api.sh the first time bc it wasn't in the instructions, but i ran it then reran build_all.sh and it worked

**Comment by wootguy** [comment]
weird, that shouldn't be necessary since build_all calls update_api. Well, glad it works now.
